Contas/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Contas.Models.ViewModel;
using Contas.Services;
using System;
using Contas.Models.Entity;
using System.Collections.Generic;

namespace Contas.Controllers {
    public class HomeController : Controller {

        public IActionResult Index() {
            IndexViewModel index = new IndexViewModel();
            var mes_atual = ConsolidadoService.GetValue("mes_atual");
            string data = "01/"+mes_atual;
            DateTime Date = Convert.ToDateTime(data);
            index.MesAtual = Date;

            List<Movimentacao> mov;

            for (int i=0;i<=5;i++) {
                mov = ContasService.GetMovimentacoes(Date.AddMonths(i));
                index.Movimentacoes.Add(mov);
                SetLinhas(mov.Count);
            }
            index.linhas = linhas;
            // PlanilhaService.AtualizarPlanilha();
            return View(index);
        }

        private int linhas;
        private int SetLinhas(int linhas) {
            if (linhas > this.linhas) {
                this.linhas = linhas;
            }
            return this.linhas;
        }

    }

}

Contas/ViewComponents/FormConsolidadosViewComponent.cs
using Contas.Models.ViewModel;
using Contas.Services;
using Microsoft.AspNetCore.Mvc;

namespace Contas.ViewComponents {
    public class FormConsolidadosViewComponent : ViewComponent {
        public IViewComponentResult Invoke() {
            var model = new FormConsolidadosViewModel();
            model.Casa = ConsolidadoService.GetValue("casa");
            model.Itau = ConsolidadoService.GetValue("itau");
            model.Inter = ConsolidadoService.GetValue("inter");
            model.Savings = ConsolidadoService.GetValue("savings");
            model.Salario = ConsolidadoService.GetValue("salario");
            model.Mensal = ConsolidadoService.GetValue("mensal");
            model.MesAtual = ConsolidadoService.GetValue("mes_atual");

            return View("FormConsolidados", model);
        }
    }
}

Contas/ViewComponents/FormMovimentacaoViewComponent.cs
using System;
using Contas.Models.ViewModel;
using Contas.Services;
using Microsoft.AspNetCore.Mvc;

namespace Contas.ViewComponents {
    public class FormMovimentacaoViewComponent : ViewComponent {
        public IViewComponentResult Invoke(FormMovimentacaoViewModel model = null) {
            if (model == null) {
                model = new FormMovimentacaoViewModel();
                model.Data = DateTime.Now.Date.ToShortDateString();
            }

            return View("FormMovimentacao", model);
        }
    }
}

Contas/ViewComponents/TabelaMesViewComponent.cs
using Contas.Models.Entity;
using Contas.Models.ViewModel;
using Contas.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Contas.Services;

namespace Contas.ViewComponents {
    public class TabelaMesViewComponent : ViewComponent {

        public IViewComponentResult Invoke(List<Movimentacao> movimentacoes, DateTime mes, int indice, int linhas) {
            var model = new TabelaMesViewModel(movimentacoes, mes, indice, linhas);
            return View("TabelaMes", model);
        }

    }
}

Contas/ViewComponents/TabelaSavingsViewComponent.cs
using Contas.Models.Entity;
using Contas.Models.ViewModel;
using Contas.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Contas.Services;

namespace Contas.ViewComponents {
    public class TabelaSavingsViewComponent : ViewComponent {

        public IViewComponentResult Invoke(DateTime mes, int indice) {
            var model = new TabelaSavingsViewModel(mes, indice, ContasService.GetSaveMes(mes));
            return View("TabelaSavings", model);
        }

    }
}

Contas/Views/Home/Index.cshtml
@model Contas.Models.ViewModel.IndexViewModel
<div class="modal fade" id="modal_consolidado" role="dialog" tabindex="-1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
                <h4 class="modal-title">Valores Consolidados</h4>
            </div>
            <div class="modal-body row">
                <form id="form_consolidado">
                    @await Component.InvokeAsync("FormConsolidados")
                </form>
            </div>
            <div class="modal-footer footer_form_consolidados">
                <button type="button" class="btn btn-primary salvar">Salvar</button>
                <button type="button" class="btn btn-primary cancelar" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal_movimentacao" role="dialog" tabindex="-1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
                <h4 class="modal-title">Movimentação</h4>
            </div>
            <div class="modal-body row">
                <form id="form_movimentacao">
                    @await Component.InvokeAsync("FormMovimentacao")
                </form>
            </div>
            <div class="modal-footer footer_form_movimentacao">
                <button type="button" class="btn btn-primary salvar">Salvar</button>
                <button type="button" class="btn btn-primary cancelar" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
<div class="row div_movimentacoes">
    @for (var i = 0; i <= 5; i++) {
        <div class="col-md-2">
            @await Component.InvokeAsync("TabelaMes", new { movimentacoes = Model.Movimentacoes[i], mes = Model.MesAtual.AddMonths(i), indice = i, linhas = Model.linhas })
        </div>
    }
    @for (var i = 0; i <= 5; i++) {
        <div class="col-md-2 tabela_saving_@i">
            @await Component.InvokeAsync("TabelaSavings", new { mes = Model.MesAtual.AddMonths(i), indice = i })
        </div>
    }
</div>